<?php

/**
 * Abstract API
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   MIT
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Api;
!defined("KRONUP-SDK") && exit();

use Kronup\Sdk;
use Kronup\Sdk\HeaderSelector;
use Kronup\Sdk\Psr7\Exception\RequestException;
use Kronup\Sdk\Psr7\Request;
use Kronup\Sdk\Psr7\Http\Client;
use Kronup\Sdk\Serializer;
use Kronup\Sdk\ApiException;

abstract class AbstractApi {
    /**
     * SDK object
     *
     * @var \Kronup\Sdk
     */
    protected $_sdk;

    /**
     * "Accept" and Content-Type header selector
     *
     * @var \Kronup\Sdk\HeaderSelector
     */
    protected $_headerSelector;

    /**
     * API Constructor
     *
     * @param Sdk $sdk API SDK object
     */
    public function __construct(Sdk $sdk) {
        $this->_sdk = $sdk;
        $this->_headerSelector = new HeaderSelector();
    }

    /**
     * Execute a request
     *
     * @param \Kronup\Sdk\Psr7\Request $request    An initialized request object.
     * @param string|null             $returnType (optional) Return type
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @return \Kronup\Model\ModelInterface|\Kronup\Sdk\Psr7\Http\ResponseInterface
     */
    protected function exec(Request $request, ?string $returnType = null) {
        // Prepare user agent info
        $userAgentExtra = [$request->getPackage()];

        // Debug mode
        if ($this->_sdk->config()->getDebug()) {
            $userAgentExtra[] = "@DEBUG";
        }

        // Set the user-agent header
        $request->setHeader(
            "User-Agent",
            sprintf("%s (%s)", $this->_sdk->config()->getUserAgent(), implode(", ", $userAgentExtra))
        );

        // Set the API key
        if (strlen($this->_sdk->config()->getApiKey())) {
            $request->setHeader("Authorization", 'Bearer ' .  $this->_sdk->config()->getApiKey());
        }

        // Accept gzip compression
        $request->setHeader("Accept-Encoding", "gzip");

        try {
            $response = Client::send($request, $this->_sdk->config());
        } catch (RequestException $exc) {
            $response = $exc->getResponse();

            throw (new ApiException(
                sprintf("[%d] Request error (%s): %s", (int) $exc->getCode(), $exc->getMessage(), $response->getBody()),
                (int) $exc->getCode(),
                $response->getHeaders(),
                $response->getBody()
            ))->setResponseObject(Serializer::deserialize($response->getBody(), "array"));
        }

        // Server error
        if ($response->getStatusCode() < 200 || $response->getStatusCode() > 299) {
            throw (new ApiException(
                sprintf("[%d] API error (%s)", $response->getStatusCode(), strval($request->getUri())),
                $response->getStatusCode(),
                $response->getHeaders(),
                $response->getBody()
            ))->setResponseObject(Serializer::deserialize($response->getBody(), "array"));
        }

        // Convert to a model
        return is_string($returnType) && strlen($returnType)
            ? Serializer::deserialize(
                $response->getBody(),
                $returnType,
                $response->getHeaders(),
                $this->_sdk->config()
            ) 
            : $response;
    }
}
