<?php

/**
 * Implementation of Experiences API
 *
 * @copyright (c) 2022-2023 kronup.io
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 *
 * NOTE: This class is auto-generated by Kronup
 * Do not edit this file manually!
 */

namespace Kronup\Api;
!defined("KRONUP-SDK") && exit();

use InvalidArgumentException as IAE;
use Kronup\Sdk\Serializer as S;

/**
 * API for Experiences
 */
class ExperiencesApi extends AbstractApi {
    
    /**
     * API package
     */
    const PKG = "Experiences";

    /**
     * Evaluate myself
     *
     * @param string $notion_id Notion ID
     * @param string $grade Grade between 1 and 10
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\Experience
     */
    public function evaluate($notion_id, $grade) {
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp/notions/{notionId}/grade/{grade}";
        
        /** @var \Kronup\Model\Experience $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "PUT", S::parse($rPath, ["notionId" => $notion_id, "grade" => $grade]), $rPath, [], $rHeaders, []
            ), 
            "\Kronup\Model\Experience"
        );
            
        return $result;
    }
    
    /**
     * Evaluate peers
     *
     * @param string $notion_id Notion ID
     * @param string $grade Grade between 1 and 10
     * @param string $user_id User ID
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\Experience
     */
    public function evaluatePeer($notion_id, $grade, $user_id) {
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp/notions/{notionId}/grade/{grade}/users/{userId}";
        
        /** @var \Kronup\Model\Experience $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "PUT", S::parse($rPath, ["notionId" => $notion_id, "grade" => $grade, "userId" => $user_id]), $rPath, [], $rHeaders, []
            ), 
            "\Kronup\Model\Experience"
        );
            
        return $result;
    }
    
    /**
     * Fetch my experiences
     *
     * @param int|1 $page_number 
     * @param int|500 $page_size 
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\ExperiencesList
     */
    public function list($page_number = 1, $page_size = 500) {
        if (isset($page_number) && $page_number < 1) {
            throw new IAE('Invalid value for "$page_number" when calling ExperiencesApi., must be bigger than or equal to 1.');
        }

        if (isset($page_size) && $page_size > 1500) {
            throw new IAE('Invalid value for "$page_size" when calling ExperiencesApi., must be smaller than or equal to 1500');
        }

        if (isset($page_size) && $page_size < 1) {
            throw new IAE('Invalid value for "$page_size" when calling ExperiencesApi., must be bigger than or equal to 1.');
        }

        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp";
        
        /** @var \Kronup\Model\ExperiencesList $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "GET", $rPath, $rPath, [
                    "pageNumber" => S::toQueryValue($page_number),
                    "pageSize" => S::toQueryValue($page_size),
                ], $rHeaders, []
            ), 
            "\Kronup\Model\ExperiencesList"
        );
            
        return $result;
    }
    
    /**
     * Fetch peer experiences
     *
     * @param string $user_id User ID
     * @param int|1 $page_number 
     * @param int|500 $page_size 
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\ExperiencesList
     */
    public function listPeer($user_id, $page_number = 1, $page_size = 500) {
        if (isset($page_number) && $page_number < 1) {
            throw new IAE('Invalid value for "$page_number" when calling ExperiencesApi., must be bigger than or equal to 1.');
        }

        if (isset($page_size) && $page_size > 1500) {
            throw new IAE('Invalid value for "$page_size" when calling ExperiencesApi., must be smaller than or equal to 1500');
        }

        if (isset($page_size) && $page_size < 1) {
            throw new IAE('Invalid value for "$page_size" when calling ExperiencesApi., must be bigger than or equal to 1.');
        }

        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp/users/{userId}";
        
        /** @var \Kronup\Model\ExperiencesList $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "GET", S::parse($rPath, ["userId" => $user_id]), $rPath, [
                    "pageNumber" => S::toQueryValue($page_number),
                    "pageSize" => S::toQueryValue($page_size),
                ], $rHeaders, []
            ), 
            "\Kronup\Model\ExperiencesList"
        );
            
        return $result;
    }
    
    /**
     * Fetch my notion experience
     *
     * @param string $notion_id Notion ID
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\Experience
     */
    public function read($notion_id) {
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp/notions/{notionId}";
        
        /** @var \Kronup\Model\Experience $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "GET", S::parse($rPath, ["notionId" => $notion_id]), $rPath, [], $rHeaders, []
            ), 
            "\Kronup\Model\Experience"
        );
            
        return $result;
    }
    
    /**
     * Fetch peer notion experience
     *
     * @param string $notion_id Notion ID
     * @param string|null $user_id User ID
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\Experience
     */
    public function readPeer($notion_id, $user_id = null) {
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        // Path template
        $rPath = "/xp/notions/{notionId}/users/{userId}";
        
        /** @var \Kronup\Model\Experience $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "GET", S::parse($rPath, ["notionId" => $notion_id, "userId" => $user_id]), $rPath, [], $rHeaders, []
            ), 
            "\Kronup\Model\Experience"
        );
            
        return $result;
    }
    
}
