<?php

/**
 * Implementation of Experience API
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Api;
!defined("KRONUP-SDK") && exit();

use InvalidArgumentException as IAE;
use Kronup\Sdk\Serializer as S;

/**
 * API for Experience
 */
class ExperienceApi extends AbstractApi {
    
    /**
     * API package
     */
    const PKG = "Experience";

    /**
     * Create keyword
     *
     * @param string $x_org_id Organization ID
     * @param \Kronup\Model\RequestKeywordCreate $request_keyword_create 
     * @throws \Kronup\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Kronup\Model\Keyword
     */
    public function keywordCreate($x_org_id, $request_keyword_create) {
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], ["application/json"]);
        $rHeaders = array_merge(
            [
                "x-org-id" => S::toHeaderValue($x_org_id),
            ], 
            $rHeaders
        );

        // Path template
        $rPath = "/keywords";
        
        /** @var \Kronup\Model\Keyword $result */
        $result = $this->exec(
            S::createRequest(
                $this->_sdk->config(), self::PKG, "POST", $rPath, $rPath, [], $rHeaders, [], $request_keyword_create
            ), 
            "\Kronup\Model\Keyword"
        );
            
        return $result;
    }
    
}
