<?php
/**
 * Autoloader
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://php.kronup.com/
 *
 * NOTE: This class is auto-generated by Kronup
 * Do not edit this file manually!
 */
spl_autoload_register(function ($className) {
    if (0 === strpos($className, "Kronup\\")) {
        // Prepare class parts
        $parts = array_slice(explode("\\", $className), 1);

        // Load the file
        require_once __DIR__ . "/lib/" . implode("/", $parts) . ".php";
    }
});