<?php

/**
 * Account__orgs Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Account__orgs Model
 */
class AccountOrgs extends AbstractModel {

    public const _D = null;
    protected static $_name = "Account__orgs";
    protected static $_definition = [
        "org_id_xxx" => ["org-id-xxx", "\Kronup\Model\AccountOrgsOrgIdXxx", null, "getOrgIdXxx", "setOrgIdXxx", null, ["r" => 0]]
    ];

    /**
     * AccountOrgs
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get org_id_xxx
     *
     * @return \Kronup\Model\AccountOrgsOrgIdXxx|null
     */
    public function getOrgIdXxx(): ?\Kronup\Model\AccountOrgsOrgIdXxx {
        return $this->_data["org_id_xxx"];
    }

    /**
     * Set org_id_xxx
     * 
     * @param \Kronup\Model\AccountOrgsOrgIdXxx|null $org_id_xxx org_id_xxx
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgIdXxx( $org_id_xxx) {
        return $this->_set("org_id_xxx", $org_id_xxx);
    }
}
