<?php

/**
 * Assessment Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Assessment Model
 */
class Assessment extends AbstractModel {

    public const _D = null;
    protected static $_name = "Assessment";
    protected static $_definition = [
        "k" => ["k", "string", null, "getK", "setK", null, ["r" => 0]], 
        "s" => ["s", "float[]", null, "getS", "setS", null, ["r" => 0, "c" => 1]], 
        "p" => ["p", "float[]", null, "getP", "setP", null, ["r" => 0, "c" => 1]]
    ];

    /**
     * Assessment
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get k
     *
     * @return string|null
     */
    public function getK(): ?string {
        return $this->_data["k"];
    }

    /**
     * Set k
     * 
     * @param string|null $k Keyword ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setK($k) {
        return $this->_set("k", $k);
    }

    /**
     * Get s
     *
     * @return float[]|null
     */
    public function getS(): ?array {
        return $this->_data["s"];
    }

    /**
     * Set s
     * 
     * @param float[]|null $s Self-assessment
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setS(?array $s) {
        return $this->_set("s", $s);
    }

    /**
     * Get p
     *
     * @return float[]|null
     */
    public function getP(): ?array {
        return $this->_data["p"];
    }

    /**
     * Set p
     * 
     * @param float[]|null $p Peer assessment
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setP(?array $p) {
        return $this->_set("p", $p);
    }
}
