<?php

/**
 * Invitation Model
 *
 * @copyright (c) 2022-2023 kronup.io
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.io/
 *
 * NOTE: This class is auto-generated by kronup.io
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Invitation Model
 */
class Invitation extends AbstractModel {

    public const _D = null;
    public const INVITE_ORG_ROLE_ADMIN = 'admin';
    public const INVITE_ORG_ROLE_MEMBER = 'member';
    protected static $_name = "Invitation";
    protected static $_definition = [
        "id" => ["id", "string", null, "getId", "setId", null, ["r" => 0]], 
        "orgId" => ["orgId", "string", null, "getOrgId", "setOrgId", null, ["r" => 0]], 
        "teamId" => ["teamId", "string", null, "getTeamId", "setTeamId", null, ["r" => 0]], 
        "userId" => ["userId", "string", null, "getUserId", "setUserId", null, ["r" => 0]], 
        "inviteName" => ["inviteName", "string", null, "getInviteName", "setInviteName", null, ["r" => 0]], 
        "inviteOrgRole" => ["inviteOrgRole", "string", null, "getInviteOrgRole", "setInviteOrgRole", null, ["r" => 0, "e" => 1]], 
        "inviteOrgName" => ["inviteOrgName", "string", null, "getInviteOrgName", "setInviteOrgName", null, ["r" => 0]], 
        "inviteUses" => ["inviteUses", "int", null, "getInviteUses", "setInviteUses", null, ["r" => 0, "n" => [0]]], 
        "inviteUsesMax" => ["inviteUsesMax", "int", null, "getInviteUsesMax", "setInviteUsesMax", null, ["r" => 0, "n" => [0], "x" => [10000]]], 
        "inviteViews" => ["inviteViews", "int", null, "getInviteViews", "setInviteViews", null, ["r" => 0, "n" => [0]]], 
        "expiresAt" => ["expiresAt", "string", null, "getExpiresAt", "setExpiresAt", null, ["r" => 0]], 
        "createdAt" => ["createdAt", "string", null, "getCreatedAt", "setCreatedAt", null, ["r" => 0]], 
        "updatedAt" => ["updatedAt", "string", null, "getUpdatedAt", "setUpdatedAt", null, ["r" => 0]]
    ];

    /**
     * Invitation
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }

    /**
     * Get allowable values
     *
     * @return string[]
     */
    public function getInviteOrgRoleAllowableValues(): array {
        return [
            self::INVITE_ORG_ROLE_ADMIN,
            self::INVITE_ORG_ROLE_MEMBER,
        ];
    }

    /**
     * Get id - Invitation ID
     *
     * @return string|null
     */
    public function getId(): ?string {
        return $this->_data["id"];
    }

    /**
     * Set id - Invitation ID
     * 
     * @param string|null $id Invitation ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setId($id) {
        return $this->_set("id", $id);
    }

    /**
     * Get orgId - Organization ID
     *
     * @return string|null
     */
    public function getOrgId(): ?string {
        return $this->_data["orgId"];
    }

    /**
     * Set orgId - Organization ID
     * 
     * @param string|null $org_id Organization ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgId($org_id) {
        return $this->_set("orgId", $org_id);
    }

    /**
     * Get teamId - Team ID
     *
     * @return string|null
     */
    public function getTeamId(): ?string {
        return $this->_data["teamId"];
    }

    /**
     * Set teamId - Team ID
     * 
     * @param string|null $team_id Team ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setTeamId($team_id) {
        return $this->_set("teamId", $team_id);
    }

    /**
     * Get userId - User ID
     *
     * @return string|null
     */
    public function getUserId(): ?string {
        return $this->_data["userId"];
    }

    /**
     * Set userId - User ID
     * 
     * @param string|null $user_id User ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setUserId($user_id) {
        return $this->_set("userId", $user_id);
    }

    /**
     * Get inviteName - Invitation name
     *
     * @return string|null
     */
    public function getInviteName(): ?string {
        return $this->_data["inviteName"];
    }

    /**
     * Set inviteName - Invitation name
     * 
     * @param string|null $invite_name Invitation name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteName($invite_name) {
        return $this->_set("inviteName", $invite_name);
    }

    /**
     * Get inviteOrgRole - Invitation user role
     *
     * @return string|null
     */
    public function getInviteOrgRole(): ?string {
        return $this->_data["inviteOrgRole"];
    }

    /**
     * Set inviteOrgRole - Invitation user role
     * 
     * @param string|null $invite_org_role Invitation user role
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteOrgRole($invite_org_role) {
        return $this->_set("inviteOrgRole", $invite_org_role);
    }

    /**
     * Get inviteOrgName - Invitation organzation name
     *
     * @return string|null
     */
    public function getInviteOrgName(): ?string {
        return $this->_data["inviteOrgName"];
    }

    /**
     * Set inviteOrgName - Invitation organzation name
     * 
     * @param string|null $invite_org_name Invitation organzation name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteOrgName($invite_org_name) {
        return $this->_set("inviteOrgName", $invite_org_name);
    }

    /**
     * Get inviteUses - Number of uses
     *
     * @return int|null
     */
    public function getInviteUses(): ?int {
        return $this->_data["inviteUses"];
    }

    /**
     * Set inviteUses - Number of uses
     * 
     * @param int|null $invite_uses Number of uses
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteUses($invite_uses) {
        return $this->_set("inviteUses", $invite_uses);
    }

    /**
     * Get inviteUsesMax - Maximum number of uses
     *
     * @return int|null
     */
    public function getInviteUsesMax(): ?int {
        return $this->_data["inviteUsesMax"];
    }

    /**
     * Set inviteUsesMax - Maximum number of uses
     * 
     * @param int|null $invite_uses_max Maximum number of uses
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteUsesMax($invite_uses_max) {
        return $this->_set("inviteUsesMax", $invite_uses_max);
    }

    /**
     * Get inviteViews - Number of views
     *
     * @return int|null
     */
    public function getInviteViews(): ?int {
        return $this->_data["inviteViews"];
    }

    /**
     * Set inviteViews - Number of views
     * 
     * @param int|null $invite_views Number of views
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setInviteViews($invite_views) {
        return $this->_set("inviteViews", $invite_views);
    }

    /**
     * Get expiresAt - Expires timestamp
     *
     * @return string|null
     */
    public function getExpiresAt(): ?string {
        return $this->_data["expiresAt"];
    }

    /**
     * Set expiresAt - Expires timestamp
     * 
     * @param string|null $expires_at Expires timestamp
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setExpiresAt($expires_at) {
        return $this->_set("expiresAt", $expires_at);
    }

    /**
     * Get createdAt - Created timestamp
     *
     * @return string|null
     */
    public function getCreatedAt(): ?string {
        return $this->_data["createdAt"];
    }

    /**
     * Set createdAt - Created timestamp
     * 
     * @param string|null $created_at Created timestamp
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setCreatedAt($created_at) {
        return $this->_set("createdAt", $created_at);
    }

    /**
     * Get updatedAt - Updated timestamp
     *
     * @return string|null
     */
    public function getUpdatedAt(): ?string {
        return $this->_data["updatedAt"];
    }

    /**
     * Set updatedAt - Updated timestamp
     * 
     * @param string|null $updated_at Updated timestamp
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setUpdatedAt($updated_at) {
        return $this->_set("updatedAt", $updated_at);
    }
}
