<?php

/**
 * Organization Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Organization Model
 */
class Organization extends AbstractModel {

    public const _D = null;
    protected static $_name = "Organization";
    protected static $_definition = [
        "id" => ["id", "string", null, "getId", "setId", null, ["r" => 0]], 
        "orgName" => ["orgName", "string", null, "getOrgName", "setOrgName", null, ["r" => 0]], 
        "orgIcon" => ["orgIcon", "string", null, "getOrgIcon", "setOrgIcon", null, ["r" => 0]], 
        "orgOwners" => ["orgOwners", "string[]", null, "getOrgOwners", "setOrgOwners", null, ["r" => 0, "c" => 1]], 
        "createdAt" => ["createdAt", "string", null, "getCreatedAt", "setCreatedAt", null, ["r" => 0]], 
        "updatedAt" => ["updatedAt", "string", null, "getUpdatedAt", "setUpdatedAt", null, ["r" => 0]]
    ];

    /**
     * Organization
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get id
     *
     * @return string|null
     */
    public function getId(): ?string {
        return $this->_data["id"];
    }

    /**
     * Set id
     * 
     * @param string|null $id Organization ID
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setId($id) {
        return $this->_set("id", $id);
    }

    /**
     * Get orgName
     *
     * @return string|null
     */
    public function getOrgName(): ?string {
        return $this->_data["orgName"];
    }

    /**
     * Set orgName
     * 
     * @param string|null $org_name Organization name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgName($org_name) {
        return $this->_set("orgName", $org_name);
    }

    /**
     * Get orgIcon
     *
     * @return string|null
     */
    public function getOrgIcon(): ?string {
        return $this->_data["orgIcon"];
    }

    /**
     * Set orgIcon
     * 
     * @param string|null $org_icon Organization logo URL
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgIcon($org_icon) {
        return $this->_set("orgIcon", $org_icon);
    }

    /**
     * Get orgOwners
     *
     * @return string[]|null
     */
    public function getOrgOwners(): ?array {
        return $this->_data["orgOwners"];
    }

    /**
     * Set orgOwners
     * 
     * @param string[]|null $org_owners Organization owners
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgOwners(?array $org_owners) {
        return $this->_set("orgOwners", $org_owners);
    }

    /**
     * Get createdAt
     *
     * @return string|null
     */
    public function getCreatedAt(): ?string {
        return $this->_data["createdAt"];
    }

    /**
     * Set createdAt
     * 
     * @param string|null $created_at Created timestamp
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setCreatedAt($created_at) {
        return $this->_set("createdAt", $created_at);
    }

    /**
     * Get updatedAt
     *
     * @return string|null
     */
    public function getUpdatedAt(): ?string {
        return $this->_data["updatedAt"];
    }

    /**
     * Set updatedAt
     * 
     * @param string|null $updated_at Updated timestamp
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setUpdatedAt($updated_at) {
        return $this->_set("updatedAt", $updated_at);
    }
}
