<?php

/**
 * organizationCreate_request Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * organizationCreate_request Model
 */
class OrganizationCreateRequest extends AbstractModel {

    public const _D = null;
    protected static $_name = "organizationCreate_request";
    protected static $_definition = [
        "org_name" => ["orgName", "string", null, "getOrgName", "setOrgName", null, ["r" => 0, "nl" => 3, "xl" => 64]]
    ];

    /**
     * OrganizationCreateRequest
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get org_name
     *
     * @return string|null
     */
    public function getOrgName(): ?string {
        return $this->_data["org_name"];
    }

    /**
     * Set org_name
     * 
     * @param string|null $org_name Organization name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setOrgName( $org_name) {
        return $this->_set("org_name", $org_name);
    }
}
