<?php

/**
 * Payload_Notion_Update Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://php.kronup.com/
 *
 * NOTE: This class is auto-generated by Kronup
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Payload_Notion_Update Model
 * 
 * Payload object required to update a Notion
 */
class PayloadNotionUpdate extends AbstractModel {

    public const _D = null;
    protected static $_name = "Payload_Notion_Update";
    protected static $_definition = [
        "value" => ["value", "string", null, "getValue", "setValue", null, ["r" => 0, "nl" => 1, "xl" => 64]]
    ];

    /**
     * PayloadNotionUpdate
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get value - Notion value
     *
     * @return string|null
     */
    public function getValue(): ?string {
        return $this->_data["value"];
    }

    /**
     * Set value - Notion value
     * 
     * @param string|null $value Notion value
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setValue($value) {
        return $this->_set("value", $value);
    }
}
