<?php

/**
 * Price_Plan_List Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://php.kronup.com/
 *
 * NOTE: This class is auto-generated by Kronup
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Price_Plan_List Model
 */
class PricePlanList extends AbstractModel {

    public const _D = null;
    protected static $_name = "Price_Plan_List";
    protected static $_definition = [
        "total" => ["total", "int", null, "getTotal", "setTotal", null, ["r" => 0]], 
        "pricePlans" => ["pricePlans", "\Kronup\Model\PricePlan[]", null, "getPricePlans", "setPricePlans", null, ["r" => 0, "c" => 1]]
    ];

    /**
     * PricePlanList
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get total - Total number of Price Plans
     *
     * @return int|null
     */
    public function getTotal(): ?int {
        return $this->_data["total"];
    }

    /**
     * Set total - Total number of Price Plans
     * 
     * @param int|null $total Total number of Price Plans
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setTotal($total) {
        return $this->_set("total", $total);
    }

    /**
     * Get pricePlans - Price Plans
     *
     * @return \Kronup\Model\PricePlan[]|null
     */
    public function getPricePlans(): ?array {
        return $this->_data["pricePlans"];
    }

    /**
     * Set pricePlans - Price Plans
     * 
     * @param \Kronup\Model\PricePlan[]|null $price_plans Price Plans
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setPricePlans(?array $price_plans) {
        return $this->_set("pricePlans", $price_plans);
    }
}
