<?php

/**
 * Request_Team_Create Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Request_Team_Create Model
 */
class RequestTeamCreate extends AbstractModel {

    public const _D = null;
    protected static $_name = "Request_Team_Create";
    protected static $_definition = [
        "teamName" => ["teamName", "string", null, "getTeamName", "setTeamName", null, ["r" => 1, "nl" => 3, "xl" => 64]], 
        "teamDesc" => ["teamDesc", "string", null, "getTeamDesc", "setTeamDesc", '', ["r" => 0, "xl" => 256]]
    ];

    /**
     * RequestTeamCreate
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get teamName
     *
     * @return string
     */
    public function getTeamName(): string {
        return $this->_data["teamName"];
    }

    /**
     * Set teamName
     * 
     * @param string $team_name Team name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setTeamName($team_name) {
        return $this->_set("teamName", $team_name);
    }

    /**
     * Get teamDesc
     *
     * @return string|null
     */
    public function getTeamDesc(): ?string {
        return $this->_data["teamDesc"];
    }

    /**
     * Set teamDesc
     * 
     * @param string|null $team_desc Team description
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setTeamDesc($team_desc) {
        return $this->_set("teamDesc", $team_desc);
    }
}
