<?php

/**
 * Request_Channel_Create Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Request_Channel_Create Model
 */
class RequestChannelCreate extends AbstractModel {

    public const _D = null;
    protected static $_name = "Request_Channel_Create";
    protected static $_definition = [
        "channelName" => ["channelName", "string", null, "getChannelName", "setChannelName", null, ["r" => 0, "nl" => 3, "xl" => 64]], 
        "channelDesc" => ["channelDesc", "string", null, "getChannelDesc", "setChannelDesc", '', ["r" => 0, "xl" => 256]]
    ];

    /**
     * RequestChannelCreate
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get channelName - Channel name
     *
     * @return string|null
     */
    public function getChannelName(): ?string {
        return $this->_data["channelName"];
    }

    /**
     * Set channelName - Channel name
     * 
     * @param string|null $channel_name Channel name
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setChannelName($channel_name) {
        return $this->_set("channelName", $channel_name);
    }

    /**
     * Get channelDesc - Channel description
     *
     * @return string|null
     */
    public function getChannelDesc(): ?string {
        return $this->_data["channelDesc"];
    }

    /**
     * Set channelDesc - Channel description
     * 
     * @param string|null $channel_desc Channel description
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setChannelDesc($channel_desc) {
        return $this->_set("channelDesc", $channel_desc);
    }
}
