<?php

/**
 * Request_Task_Feedback_Create Model
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Model;
!defined("KRONUP-SDK") && exit();

/**
 * Request_Task_Feedback_Create Model
 */
class RequestTaskFeedbackCreate extends AbstractModel {

    public const _D = null;
    protected static $_name = "Request_Task_Feedback_Create";
    protected static $_definition = [
        "message" => ["message", "string", null, "getMessage", "setMessage", null, ["r" => 0, "nl" => 1, "xl" => 1024]], 
        "issue" => ["issue", "string", null, "getIssue", "setIssue", null, ["r" => 0]]
    ];

    /**
     * RequestTaskFeedbackCreate
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get message
     *
     * @return string|null
     */
    public function getMessage(): ?string {
        return $this->_data["message"];
    }

    /**
     * Set message
     * 
     * @param string|null $message Feedback details
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setMessage($message) {
        return $this->_set("message", $message);
    }

    /**
     * Get issue
     *
     * @return string|null
     */
    public function getIssue(): ?string {
        return $this->_data["issue"];
    }

    /**
     * Set issue
     * 
     * @param string|null $issue Feedback issue
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setIssue($issue) {
        return $this->_set("issue", $issue);
    }
}
