<?php

/**
 * Kronup SDK Caller - API
 *
 * @copyright (c) 2022-2023 kronup.com
 * @license   Apache 2.0
 * @package   Kronup
 * @author    Mark Jivko
 * @link      https://kronup.com/
 *
 * NOTE: This class is auto-generated by kronup.com
 * Do not edit this file manually!
 */

namespace Kronup\Sdk\Caller;
!defined("KRONUP-SDK") && exit();

use Kronup\Sdk;
use Kronup\Api as A;

class Api {
    /**
     * SDK object
     *
     * @var \Kronup\Sdk
     */
    protected $_sdk;

    /**
     * Account API
     *
     * @var \Kronup\Api\AccountApi
     */
    protected $_accountApi = null;

    /**
     * Invitations API
     *
     * @var \Kronup\Api\InvitationsApi
     */
    protected $_invitationsApi = null;

    /**
     * Organizations API
     *
     * @var \Kronup\Api\OrganizationsApi
     */
    protected $_organizationsApi = null;

    /**
     * Users API
     *
     * @var \Kronup\Api\UsersApi
     */
    protected $_usersApi = null;

    /**
     * SDK 
     *
     * @param \Kronup\Sdk $sdk SDK object
     */
    public function __construct(Sdk $sdk) {
        $this->_sdk = $sdk;
    }
    
    /**
     * Account API
     * 
     * @return \Kronup\Api\AccountApi
     */
    public function account(): A\AccountApi {
        if (null === $this->_accountApi) {
            $this->_accountApi = new A\AccountApi($this->_sdk);
        }

        return $this->_accountApi;
    }
    
    /**
     * Invitations API
     * 
     * @return \Kronup\Api\InvitationsApi
     */
    public function invitations(): A\InvitationsApi {
        if (null === $this->_invitationsApi) {
            $this->_invitationsApi = new A\InvitationsApi($this->_sdk);
        }

        return $this->_invitationsApi;
    }
    
    /**
     * Organizations API
     * 
     * @return \Kronup\Api\OrganizationsApi
     */
    public function organizations(): A\OrganizationsApi {
        if (null === $this->_organizationsApi) {
            $this->_organizationsApi = new A\OrganizationsApi($this->_sdk);
        }

        return $this->_organizationsApi;
    }
    
    /**
     * Users API
     * 
     * @return \Kronup\Api\UsersApi
     */
    public function users(): A\UsersApi {
        if (null === $this->_usersApi) {
            $this->_usersApi = new A\UsersApi($this->_sdk);
        }

        return $this->_usersApi;
    }
}
